vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        img_avatars:
            uri_prefix: /uploads/img/avatars
            upload_destination: '%upload_directory_img_avatars%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer